import "../styles/globals.css";
import { StoreProvider } from "@/utils/store";
import { title } from "process";
import Container from "@/components/container";

export const metadata = {
  title: title ? title : "TS-Ecommerce",
  description: "Generated by rutes.co.id",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <StoreProvider>
            <Container>{children}</Container>
        </StoreProvider>
      </body>
    </html>
  );
}
